package bouquet.infrastructure.datasource.autogen.inventories;

import bouquet.domain.model.autogen.inventories.ArrivalLine;
import org.apache.ibatis.annotations.*;

public interface ArrivalLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.arrival_line
     *
     * @mbg.generated
     */
    @Delete({
            "delete from inventories.arrival_line",
            "where arrival_number = #{arrivalNumber,jdbcType=INTEGER}",
            "and arrival_line_number = #{arrivalLineNumber,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(@Param("arrivalNumber") Integer arrivalNumber, @Param("arrivalLineNumber") Integer arrivalLineNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.arrival_line
     *
     * @mbg.generated
     */
    @Insert({
            "insert into inventories.arrival_line (arrival_number, arrival_line_number, ",
            "product_number, product_name, ",
            "supplier_number, supplier_line_number, ",
            "quantity, created_by, ",
            "created_at)",
            "values (#{arrivalNumber,jdbcType=INTEGER}, #{arrivalLineNumber,jdbcType=INTEGER}, ",
            "#{productNumber,jdbcType=INTEGER}, #{productName,jdbcType=VARCHAR}, ",
            "#{supplierNumber,jdbcType=INTEGER}, #{supplierLineNumber,jdbcType=INTEGER}, ",
            "#{quantity,jdbcType=INTEGER}, #{createdBy,jdbcType=VARCHAR}, ",
            "#{createdAt,jdbcType=TIMESTAMP})"
    })
    int insert(ArrivalLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.arrival_line
     *
     * @mbg.generated
     */
    int insertSelective(ArrivalLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.arrival_line
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "arrival_number, arrival_line_number, product_number, product_name, supplier_number, ",
            "supplier_line_number, quantity, created_by, created_at",
            "from inventories.arrival_line",
            "where arrival_number = #{arrivalNumber,jdbcType=INTEGER}",
            "and arrival_line_number = #{arrivalLineNumber,jdbcType=INTEGER}"
    })
    @ResultMap("bouquet.infrastructure.datasource.autogen.inventories.ArrivalLineMapper.BaseResultMap")
    ArrivalLine selectByPrimaryKey(@Param("arrivalNumber") Integer arrivalNumber, @Param("arrivalLineNumber") Integer arrivalLineNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.arrival_line
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ArrivalLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.arrival_line
     *
     * @mbg.generated
     */
    @Update({
            "update inventories.arrival_line",
            "set product_number = #{productNumber,jdbcType=INTEGER},",
            "product_name = #{productName,jdbcType=VARCHAR},",
            "supplier_number = #{supplierNumber,jdbcType=INTEGER},",
            "supplier_line_number = #{supplierLineNumber,jdbcType=INTEGER},",
            "quantity = #{quantity,jdbcType=INTEGER},",
            "created_by = #{createdBy,jdbcType=VARCHAR},",
            "created_at = #{createdAt,jdbcType=TIMESTAMP}",
            "where arrival_number = #{arrivalNumber,jdbcType=INTEGER}",
            "and arrival_line_number = #{arrivalLineNumber,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ArrivalLine record);
}
