package bouquet.infrastructure.datasource.autogen.inventories;

import bouquet.domain.model.autogen.inventories.PlacementOrder;
import org.apache.ibatis.annotations.*;

public interface PlacementOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.placement_order
     *
     * @mbg.generated
     */
    @Delete({
            "delete from inventories.placement_order",
            "where placement_order_number = #{placementOrderNumber,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer placementOrderNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.placement_order
     *
     * @mbg.generated
     */
    @Insert({
            "insert into inventories.placement_order (placement_order_number, placement_order_date, ",
            "supplier_number, supplier_line_number, ",
            "delivery_date, placement_order_total_price_amount, ",
            "placement_order_total_tax_amount, created_by, ",
            "created_at)",
            "values (#{placementOrderNumber,jdbcType=INTEGER}, #{placementOrderDate,jdbcType=DATE}, ",
            "#{supplierNumber,jdbcType=INTEGER}, #{supplierLineNumber,jdbcType=INTEGER}, ",
            "#{deliveryDate,jdbcType=DATE}, #{placementOrderTotalPriceAmount,jdbcType=NUMERIC}, ",
            "#{placementOrderTotalTaxAmount,jdbcType=NUMERIC}, #{createdBy,jdbcType=VARCHAR}, ",
            "#{createdAt,jdbcType=TIMESTAMP})"
    })
    int insert(PlacementOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.placement_order
     *
     * @mbg.generated
     */
    int insertSelective(PlacementOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.placement_order
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "placement_order_number, placement_order_date, supplier_number, supplier_line_number, ",
            "delivery_date, placement_order_total_price_amount, placement_order_total_tax_amount, ",
            "created_by, created_at",
            "from inventories.placement_order",
            "where placement_order_number = #{placementOrderNumber,jdbcType=INTEGER}"
    })
    @ResultMap("bouquet.infrastructure.datasource.autogen.inventories.PlacementOrderMapper.BaseResultMap")
    PlacementOrder selectByPrimaryKey(Integer placementOrderNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.placement_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PlacementOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.placement_order
     *
     * @mbg.generated
     */
    @Update({
            "update inventories.placement_order",
            "set placement_order_date = #{placementOrderDate,jdbcType=DATE},",
            "supplier_number = #{supplierNumber,jdbcType=INTEGER},",
            "supplier_line_number = #{supplierLineNumber,jdbcType=INTEGER},",
            "delivery_date = #{deliveryDate,jdbcType=DATE},",
            "placement_order_total_price_amount = #{placementOrderTotalPriceAmount,jdbcType=NUMERIC},",
            "placement_order_total_tax_amount = #{placementOrderTotalTaxAmount,jdbcType=NUMERIC},",
            "created_by = #{createdBy,jdbcType=VARCHAR},",
            "created_at = #{createdAt,jdbcType=TIMESTAMP}",
            "where placement_order_number = #{placementOrderNumber,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PlacementOrder record);
}
