package bouquet.infrastructure.datasource.autogen.inventories;

import bouquet.domain.model.autogen.inventories.PurchaseLine;
import org.apache.ibatis.annotations.*;

public interface PurchaseLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.purchase_line
     *
     * @mbg.generated
     */
    @Delete({
            "delete from inventories.purchase_line",
            "where purchase_number = #{purchaseNumber,jdbcType=INTEGER}",
            "and purchase_line_number = #{purchaseLineNumber,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(@Param("purchaseNumber") Integer purchaseNumber, @Param("purchaseLineNumber") Integer purchaseLineNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.purchase_line
     *
     * @mbg.generated
     */
    @Insert({
            "insert into inventories.purchase_line (purchase_number, purchase_line_number, ",
            "product_number, product_name, ",
            "purchase_price, purchase_quantity, ",
            "created_by, created_at)",
            "values (#{purchaseNumber,jdbcType=INTEGER}, #{purchaseLineNumber,jdbcType=INTEGER}, ",
            "#{productNumber,jdbcType=INTEGER}, #{productName,jdbcType=VARCHAR}, ",
            "#{purchasePrice,jdbcType=NUMERIC}, #{purchaseQuantity,jdbcType=INTEGER}, ",
            "#{createdBy,jdbcType=VARCHAR}, #{createdAt,jdbcType=TIMESTAMP})"
    })
    int insert(PurchaseLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.purchase_line
     *
     * @mbg.generated
     */
    int insertSelective(PurchaseLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.purchase_line
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "purchase_number, purchase_line_number, product_number, product_name, purchase_price, ",
            "purchase_quantity, created_by, created_at",
            "from inventories.purchase_line",
            "where purchase_number = #{purchaseNumber,jdbcType=INTEGER}",
            "and purchase_line_number = #{purchaseLineNumber,jdbcType=INTEGER}"
    })
    @ResultMap("bouquet.infrastructure.datasource.autogen.inventories.PurchaseLineMapper.BaseResultMap")
    PurchaseLine selectByPrimaryKey(@Param("purchaseNumber") Integer purchaseNumber, @Param("purchaseLineNumber") Integer purchaseLineNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.purchase_line
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PurchaseLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.purchase_line
     *
     * @mbg.generated
     */
    @Update({
            "update inventories.purchase_line",
            "set product_number = #{productNumber,jdbcType=INTEGER},",
            "product_name = #{productName,jdbcType=VARCHAR},",
            "purchase_price = #{purchasePrice,jdbcType=NUMERIC},",
            "purchase_quantity = #{purchaseQuantity,jdbcType=INTEGER},",
            "created_by = #{createdBy,jdbcType=VARCHAR},",
            "created_at = #{createdAt,jdbcType=TIMESTAMP}",
            "where purchase_number = #{purchaseNumber,jdbcType=INTEGER}",
            "and purchase_line_number = #{purchaseLineNumber,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PurchaseLine record);
}
