package bouquet.infrastructure.datasource.autogen.inventories;

import bouquet.domain.model.autogen.inventories.Purchase;
import org.apache.ibatis.annotations.*;

public interface PurchaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.purchase
     *
     * @mbg.generated
     */
    @Delete({
            "delete from inventories.purchase",
            "where purchase_number = #{purchaseNumber,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer purchaseNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.purchase
     *
     * @mbg.generated
     */
    @Insert({
            "insert into inventories.purchase (purchase_number, purchase_date, ",
            "supplier_number, supplier_line_number, ",
            "total_purchase_amount, total_purchase_tax_amount, ",
            "created_by, created_at)",
            "values (#{purchaseNumber,jdbcType=INTEGER}, #{purchaseDate,jdbcType=DATE}, ",
            "#{supplierNumber,jdbcType=INTEGER}, #{supplierLineNumber,jdbcType=INTEGER}, ",
            "#{totalPurchaseAmount,jdbcType=NUMERIC}, #{totalPurchaseTaxAmount,jdbcType=NUMERIC}, ",
            "#{createdBy,jdbcType=VARCHAR}, #{createdAt,jdbcType=TIMESTAMP})"
    })
    int insert(Purchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.purchase
     *
     * @mbg.generated
     */
    int insertSelective(Purchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.purchase
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "purchase_number, purchase_date, supplier_number, supplier_line_number, total_purchase_amount, ",
            "total_purchase_tax_amount, created_by, created_at",
            "from inventories.purchase",
            "where purchase_number = #{purchaseNumber,jdbcType=INTEGER}"
    })
    @ResultMap("bouquet.infrastructure.datasource.autogen.inventories.PurchaseMapper.BaseResultMap")
    Purchase selectByPrimaryKey(Integer purchaseNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.purchase
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Purchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.purchase
     *
     * @mbg.generated
     */
    @Update({
            "update inventories.purchase",
            "set purchase_date = #{purchaseDate,jdbcType=DATE},",
            "supplier_number = #{supplierNumber,jdbcType=INTEGER},",
            "supplier_line_number = #{supplierLineNumber,jdbcType=INTEGER},",
            "total_purchase_amount = #{totalPurchaseAmount,jdbcType=NUMERIC},",
            "total_purchase_tax_amount = #{totalPurchaseTaxAmount,jdbcType=NUMERIC},",
            "created_by = #{createdBy,jdbcType=VARCHAR},",
            "created_at = #{createdAt,jdbcType=TIMESTAMP}",
            "where purchase_number = #{purchaseNumber,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Purchase record);
}
