package bouquet.infrastructure.datasource.autogen.inventories;

import bouquet.domain.model.autogen.inventories.Supplier;
import org.apache.ibatis.annotations.*;

public interface SupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.supplier
     *
     * @mbg.generated
     */
    @Delete({
            "delete from inventories.supplier",
            "where supplier_number = #{supplierNumber,jdbcType=INTEGER}",
            "and supplier_line_number = #{supplierLineNumber,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(@Param("supplierNumber") Integer supplierNumber, @Param("supplierLineNumber") Integer supplierLineNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.supplier
     *
     * @mbg.generated
     */
    @Insert({
            "insert into inventories.supplier (supplier_number, supplier_line_number, ",
            "supplier_code, supplier_name, ",
            "created_by, created_at)",
            "values (#{supplierNumber,jdbcType=INTEGER}, #{supplierLineNumber,jdbcType=INTEGER}, ",
            "#{supplierCode,jdbcType=VARCHAR}, #{supplierName,jdbcType=VARCHAR}, ",
            "#{createdBy,jdbcType=VARCHAR}, #{createdAt,jdbcType=TIMESTAMP})"
    })
    int insert(Supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.supplier
     *
     * @mbg.generated
     */
    int insertSelective(Supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.supplier
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "supplier_number, supplier_line_number, supplier_code, supplier_name, created_by, ",
            "created_at",
            "from inventories.supplier",
            "where supplier_number = #{supplierNumber,jdbcType=INTEGER}",
            "and supplier_line_number = #{supplierLineNumber,jdbcType=INTEGER}"
    })
    @ResultMap("bouquet.infrastructure.datasource.autogen.inventories.SupplierMapper.BaseResultMap")
    Supplier selectByPrimaryKey(@Param("supplierNumber") Integer supplierNumber, @Param("supplierLineNumber") Integer supplierLineNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.supplier
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories.supplier
     *
     * @mbg.generated
     */
    @Update({
            "update inventories.supplier",
            "set supplier_code = #{supplierCode,jdbcType=VARCHAR},",
            "supplier_name = #{supplierName,jdbcType=VARCHAR},",
            "created_by = #{createdBy,jdbcType=VARCHAR},",
            "created_at = #{createdAt,jdbcType=TIMESTAMP}",
            "where supplier_number = #{supplierNumber,jdbcType=INTEGER}",
            "and supplier_line_number = #{supplierLineNumber,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Supplier record);
}
