package bouquet.domain.model.autogen.inventories;

import java.util.Date;

public class Arrival {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.arrival.arrival_number
     *
     * @mbg.generated
     */
    private Integer arrivalNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.arrival.arrival_date
     *
     * @mbg.generated
     */
    private Date arrivalDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.arrival.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.arrival.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.arrival.arrival_number
     *
     * @return the value of inventories.arrival.arrival_number
     * @mbg.generated
     */
    public Integer getArrivalNumber() {
        return arrivalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.arrival.arrival_number
     *
     * @param arrivalNumber the value for inventories.arrival.arrival_number
     * @mbg.generated
     */
    public void setArrivalNumber(Integer arrivalNumber) {
        this.arrivalNumber = arrivalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.arrival.arrival_date
     *
     * @return the value of inventories.arrival.arrival_date
     * @mbg.generated
     */
    public Date getArrivalDate() {
        return arrivalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.arrival.arrival_date
     *
     * @param arrivalDate the value for inventories.arrival.arrival_date
     * @mbg.generated
     */
    public void setArrivalDate(Date arrivalDate) {
        this.arrivalDate = arrivalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.arrival.created_by
     *
     * @return the value of inventories.arrival.created_by
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.arrival.created_by
     *
     * @param createdBy the value for inventories.arrival.created_by
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.arrival.created_at
     *
     * @return the value of inventories.arrival.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.arrival.created_at
     *
     * @param createdAt the value for inventories.arrival.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}
