package bouquet.domain.model.autogen.inventories;

import java.util.Date;

public class ArrivalLine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.arrival_line.arrival_number
     *
     * @mbg.generated
     */
    private Integer arrivalNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.arrival_line.arrival_line_number
     *
     * @mbg.generated
     */
    private Integer arrivalLineNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.arrival_line.product_number
     *
     * @mbg.generated
     */
    private Integer productNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.arrival_line.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.arrival_line.supplier_number
     *
     * @mbg.generated
     */
    private Integer supplierNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.arrival_line.supplier_line_number
     *
     * @mbg.generated
     */
    private Integer supplierLineNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.arrival_line.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.arrival_line.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.arrival_line.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.arrival_line.arrival_number
     *
     * @return the value of inventories.arrival_line.arrival_number
     * @mbg.generated
     */
    public Integer getArrivalNumber() {
        return arrivalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.arrival_line.arrival_number
     *
     * @param arrivalNumber the value for inventories.arrival_line.arrival_number
     * @mbg.generated
     */
    public void setArrivalNumber(Integer arrivalNumber) {
        this.arrivalNumber = arrivalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.arrival_line.arrival_line_number
     *
     * @return the value of inventories.arrival_line.arrival_line_number
     * @mbg.generated
     */
    public Integer getArrivalLineNumber() {
        return arrivalLineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.arrival_line.arrival_line_number
     *
     * @param arrivalLineNumber the value for inventories.arrival_line.arrival_line_number
     * @mbg.generated
     */
    public void setArrivalLineNumber(Integer arrivalLineNumber) {
        this.arrivalLineNumber = arrivalLineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.arrival_line.product_number
     *
     * @return the value of inventories.arrival_line.product_number
     * @mbg.generated
     */
    public Integer getProductNumber() {
        return productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.arrival_line.product_number
     *
     * @param productNumber the value for inventories.arrival_line.product_number
     * @mbg.generated
     */
    public void setProductNumber(Integer productNumber) {
        this.productNumber = productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.arrival_line.product_name
     *
     * @return the value of inventories.arrival_line.product_name
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.arrival_line.product_name
     *
     * @param productName the value for inventories.arrival_line.product_name
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.arrival_line.supplier_number
     *
     * @return the value of inventories.arrival_line.supplier_number
     * @mbg.generated
     */
    public Integer getSupplierNumber() {
        return supplierNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.arrival_line.supplier_number
     *
     * @param supplierNumber the value for inventories.arrival_line.supplier_number
     * @mbg.generated
     */
    public void setSupplierNumber(Integer supplierNumber) {
        this.supplierNumber = supplierNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.arrival_line.supplier_line_number
     *
     * @return the value of inventories.arrival_line.supplier_line_number
     * @mbg.generated
     */
    public Integer getSupplierLineNumber() {
        return supplierLineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.arrival_line.supplier_line_number
     *
     * @param supplierLineNumber the value for inventories.arrival_line.supplier_line_number
     * @mbg.generated
     */
    public void setSupplierLineNumber(Integer supplierLineNumber) {
        this.supplierLineNumber = supplierLineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.arrival_line.quantity
     *
     * @return the value of inventories.arrival_line.quantity
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.arrival_line.quantity
     *
     * @param quantity the value for inventories.arrival_line.quantity
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.arrival_line.created_by
     *
     * @return the value of inventories.arrival_line.created_by
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.arrival_line.created_by
     *
     * @param createdBy the value for inventories.arrival_line.created_by
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.arrival_line.created_at
     *
     * @return the value of inventories.arrival_line.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.arrival_line.created_at
     *
     * @param createdAt the value for inventories.arrival_line.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}
