package bouquet.domain.model.autogen.inventories;

import java.util.Date;

public class Inventory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.inventory.product_number
     *
     * @mbg.generated
     */
    private Integer productNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.inventory.lot_number
     *
     * @mbg.generated
     */
    private Integer lotNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.inventory.inventory_type
     *
     * @mbg.generated
     */
    private String inventoryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.inventory.inventory_quantity
     *
     * @mbg.generated
     */
    private Integer inventoryQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.inventory.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.inventory.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.inventory.product_number
     *
     * @return the value of inventories.inventory.product_number
     * @mbg.generated
     */
    public Integer getProductNumber() {
        return productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.inventory.product_number
     *
     * @param productNumber the value for inventories.inventory.product_number
     * @mbg.generated
     */
    public void setProductNumber(Integer productNumber) {
        this.productNumber = productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.inventory.lot_number
     *
     * @return the value of inventories.inventory.lot_number
     * @mbg.generated
     */
    public Integer getLotNumber() {
        return lotNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.inventory.lot_number
     *
     * @param lotNumber the value for inventories.inventory.lot_number
     * @mbg.generated
     */
    public void setLotNumber(Integer lotNumber) {
        this.lotNumber = lotNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.inventory.inventory_type
     *
     * @return the value of inventories.inventory.inventory_type
     * @mbg.generated
     */
    public String getInventoryType() {
        return inventoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.inventory.inventory_type
     *
     * @param inventoryType the value for inventories.inventory.inventory_type
     * @mbg.generated
     */
    public void setInventoryType(String inventoryType) {
        this.inventoryType = inventoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.inventory.inventory_quantity
     *
     * @return the value of inventories.inventory.inventory_quantity
     * @mbg.generated
     */
    public Integer getInventoryQuantity() {
        return inventoryQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.inventory.inventory_quantity
     *
     * @param inventoryQuantity the value for inventories.inventory.inventory_quantity
     * @mbg.generated
     */
    public void setInventoryQuantity(Integer inventoryQuantity) {
        this.inventoryQuantity = inventoryQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.inventory.created_by
     *
     * @return the value of inventories.inventory.created_by
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.inventory.created_by
     *
     * @param createdBy the value for inventories.inventory.created_by
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.inventory.created_at
     *
     * @return the value of inventories.inventory.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.inventory.created_at
     *
     * @param createdAt the value for inventories.inventory.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}
