package bouquet.domain.model.autogen.inventories;

import java.util.Date;

public class Item {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.item.product_number
     *
     * @mbg.generated
     */
    private Integer productNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.item.item_number
     *
     * @mbg.generated
     */
    private Integer itemNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.item.item_code
     *
     * @mbg.generated
     */
    private String itemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.item.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.item.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.item.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.item.product_number
     *
     * @return the value of inventories.item.product_number
     * @mbg.generated
     */
    public Integer getProductNumber() {
        return productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.item.product_number
     *
     * @param productNumber the value for inventories.item.product_number
     * @mbg.generated
     */
    public void setProductNumber(Integer productNumber) {
        this.productNumber = productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.item.item_number
     *
     * @return the value of inventories.item.item_number
     * @mbg.generated
     */
    public Integer getItemNumber() {
        return itemNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.item.item_number
     *
     * @param itemNumber the value for inventories.item.item_number
     * @mbg.generated
     */
    public void setItemNumber(Integer itemNumber) {
        this.itemNumber = itemNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.item.item_code
     *
     * @return the value of inventories.item.item_code
     * @mbg.generated
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.item.item_code
     *
     * @param itemCode the value for inventories.item.item_code
     * @mbg.generated
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.item.quantity
     *
     * @return the value of inventories.item.quantity
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.item.quantity
     *
     * @param quantity the value for inventories.item.quantity
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.item.created_by
     *
     * @return the value of inventories.item.created_by
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.item.created_by
     *
     * @param createdBy the value for inventories.item.created_by
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.item.created_at
     *
     * @return the value of inventories.item.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.item.created_at
     *
     * @param createdAt the value for inventories.item.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}
