package bouquet.domain.model.autogen.inventories;

import java.util.Date;

public class PlacementOrderLine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.placement_order_line.placement_order_number
     *
     * @mbg.generated
     */
    private Integer placementOrderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.placement_order_line.placement_order_line_number
     *
     * @mbg.generated
     */
    private Integer placementOrderLineNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.placement_order_line.product_number
     *
     * @mbg.generated
     */
    private Integer productNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.placement_order_line.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.placement_order_line.cost_price
     *
     * @mbg.generated
     */
    private Integer costPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.placement_order_line.placement_order_line_quantity
     *
     * @mbg.generated
     */
    private Integer placementOrderLineQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.placement_order_line.arrived_quantity
     *
     * @mbg.generated
     */
    private Integer arrivedQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.placement_order_line.complete
     *
     * @mbg.generated
     */
    private Integer complete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.placement_order_line.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.placement_order_line.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.placement_order_line.placement_order_number
     *
     * @return the value of inventories.placement_order_line.placement_order_number
     * @mbg.generated
     */
    public Integer getPlacementOrderNumber() {
        return placementOrderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.placement_order_line.placement_order_number
     *
     * @param placementOrderNumber the value for inventories.placement_order_line.placement_order_number
     * @mbg.generated
     */
    public void setPlacementOrderNumber(Integer placementOrderNumber) {
        this.placementOrderNumber = placementOrderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.placement_order_line.placement_order_line_number
     *
     * @return the value of inventories.placement_order_line.placement_order_line_number
     * @mbg.generated
     */
    public Integer getPlacementOrderLineNumber() {
        return placementOrderLineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.placement_order_line.placement_order_line_number
     *
     * @param placementOrderLineNumber the value for inventories.placement_order_line.placement_order_line_number
     * @mbg.generated
     */
    public void setPlacementOrderLineNumber(Integer placementOrderLineNumber) {
        this.placementOrderLineNumber = placementOrderLineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.placement_order_line.product_number
     *
     * @return the value of inventories.placement_order_line.product_number
     * @mbg.generated
     */
    public Integer getProductNumber() {
        return productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.placement_order_line.product_number
     *
     * @param productNumber the value for inventories.placement_order_line.product_number
     * @mbg.generated
     */
    public void setProductNumber(Integer productNumber) {
        this.productNumber = productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.placement_order_line.product_name
     *
     * @return the value of inventories.placement_order_line.product_name
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.placement_order_line.product_name
     *
     * @param productName the value for inventories.placement_order_line.product_name
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.placement_order_line.cost_price
     *
     * @return the value of inventories.placement_order_line.cost_price
     * @mbg.generated
     */
    public Integer getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.placement_order_line.cost_price
     *
     * @param costPrice the value for inventories.placement_order_line.cost_price
     * @mbg.generated
     */
    public void setCostPrice(Integer costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.placement_order_line.placement_order_line_quantity
     *
     * @return the value of inventories.placement_order_line.placement_order_line_quantity
     * @mbg.generated
     */
    public Integer getPlacementOrderLineQuantity() {
        return placementOrderLineQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.placement_order_line.placement_order_line_quantity
     *
     * @param placementOrderLineQuantity the value for inventories.placement_order_line.placement_order_line_quantity
     * @mbg.generated
     */
    public void setPlacementOrderLineQuantity(Integer placementOrderLineQuantity) {
        this.placementOrderLineQuantity = placementOrderLineQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.placement_order_line.arrived_quantity
     *
     * @return the value of inventories.placement_order_line.arrived_quantity
     * @mbg.generated
     */
    public Integer getArrivedQuantity() {
        return arrivedQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.placement_order_line.arrived_quantity
     *
     * @param arrivedQuantity the value for inventories.placement_order_line.arrived_quantity
     * @mbg.generated
     */
    public void setArrivedQuantity(Integer arrivedQuantity) {
        this.arrivedQuantity = arrivedQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.placement_order_line.complete
     *
     * @return the value of inventories.placement_order_line.complete
     * @mbg.generated
     */
    public Integer getComplete() {
        return complete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.placement_order_line.complete
     *
     * @param complete the value for inventories.placement_order_line.complete
     * @mbg.generated
     */
    public void setComplete(Integer complete) {
        this.complete = complete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.placement_order_line.created_by
     *
     * @return the value of inventories.placement_order_line.created_by
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.placement_order_line.created_by
     *
     * @param createdBy the value for inventories.placement_order_line.created_by
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.placement_order_line.created_at
     *
     * @return the value of inventories.placement_order_line.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.placement_order_line.created_at
     *
     * @param createdAt the value for inventories.placement_order_line.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}
