package bouquet.domain.model.autogen.inventories;

import java.util.Date;

public class PlacementOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.placement_order.placement_order_number
     *
     * @mbg.generated
     */
    private Integer placementOrderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.placement_order.placement_order_date
     *
     * @mbg.generated
     */
    private Date placementOrderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.placement_order.supplier_number
     *
     * @mbg.generated
     */
    private Integer supplierNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.placement_order.supplier_line_number
     *
     * @mbg.generated
     */
    private Integer supplierLineNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.placement_order.delivery_date
     *
     * @mbg.generated
     */
    private Date deliveryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.placement_order.placement_order_total_price_amount
     *
     * @mbg.generated
     */
    private Long placementOrderTotalPriceAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.placement_order.placement_order_total_tax_amount
     *
     * @mbg.generated
     */
    private Long placementOrderTotalTaxAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.placement_order.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.placement_order.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.placement_order.placement_order_number
     *
     * @return the value of inventories.placement_order.placement_order_number
     * @mbg.generated
     */
    public Integer getPlacementOrderNumber() {
        return placementOrderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.placement_order.placement_order_number
     *
     * @param placementOrderNumber the value for inventories.placement_order.placement_order_number
     * @mbg.generated
     */
    public void setPlacementOrderNumber(Integer placementOrderNumber) {
        this.placementOrderNumber = placementOrderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.placement_order.placement_order_date
     *
     * @return the value of inventories.placement_order.placement_order_date
     * @mbg.generated
     */
    public Date getPlacementOrderDate() {
        return placementOrderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.placement_order.placement_order_date
     *
     * @param placementOrderDate the value for inventories.placement_order.placement_order_date
     * @mbg.generated
     */
    public void setPlacementOrderDate(Date placementOrderDate) {
        this.placementOrderDate = placementOrderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.placement_order.supplier_number
     *
     * @return the value of inventories.placement_order.supplier_number
     * @mbg.generated
     */
    public Integer getSupplierNumber() {
        return supplierNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.placement_order.supplier_number
     *
     * @param supplierNumber the value for inventories.placement_order.supplier_number
     * @mbg.generated
     */
    public void setSupplierNumber(Integer supplierNumber) {
        this.supplierNumber = supplierNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.placement_order.supplier_line_number
     *
     * @return the value of inventories.placement_order.supplier_line_number
     * @mbg.generated
     */
    public Integer getSupplierLineNumber() {
        return supplierLineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.placement_order.supplier_line_number
     *
     * @param supplierLineNumber the value for inventories.placement_order.supplier_line_number
     * @mbg.generated
     */
    public void setSupplierLineNumber(Integer supplierLineNumber) {
        this.supplierLineNumber = supplierLineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.placement_order.delivery_date
     *
     * @return the value of inventories.placement_order.delivery_date
     * @mbg.generated
     */
    public Date getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.placement_order.delivery_date
     *
     * @param deliveryDate the value for inventories.placement_order.delivery_date
     * @mbg.generated
     */
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.placement_order.placement_order_total_price_amount
     *
     * @return the value of inventories.placement_order.placement_order_total_price_amount
     * @mbg.generated
     */
    public Long getPlacementOrderTotalPriceAmount() {
        return placementOrderTotalPriceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.placement_order.placement_order_total_price_amount
     *
     * @param placementOrderTotalPriceAmount the value for inventories.placement_order.placement_order_total_price_amount
     * @mbg.generated
     */
    public void setPlacementOrderTotalPriceAmount(Long placementOrderTotalPriceAmount) {
        this.placementOrderTotalPriceAmount = placementOrderTotalPriceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.placement_order.placement_order_total_tax_amount
     *
     * @return the value of inventories.placement_order.placement_order_total_tax_amount
     * @mbg.generated
     */
    public Long getPlacementOrderTotalTaxAmount() {
        return placementOrderTotalTaxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.placement_order.placement_order_total_tax_amount
     *
     * @param placementOrderTotalTaxAmount the value for inventories.placement_order.placement_order_total_tax_amount
     * @mbg.generated
     */
    public void setPlacementOrderTotalTaxAmount(Long placementOrderTotalTaxAmount) {
        this.placementOrderTotalTaxAmount = placementOrderTotalTaxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.placement_order.created_by
     *
     * @return the value of inventories.placement_order.created_by
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.placement_order.created_by
     *
     * @param createdBy the value for inventories.placement_order.created_by
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.placement_order.created_at
     *
     * @return the value of inventories.placement_order.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.placement_order.created_at
     *
     * @param createdAt the value for inventories.placement_order.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}
