package bouquet.domain.model.autogen.inventories;

import java.util.Date;

public class Purchase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.purchase.purchase_number
     *
     * @mbg.generated
     */
    private Integer purchaseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.purchase.purchase_date
     *
     * @mbg.generated
     */
    private Date purchaseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.purchase.supplier_number
     *
     * @mbg.generated
     */
    private Integer supplierNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.purchase.supplier_line_number
     *
     * @mbg.generated
     */
    private Integer supplierLineNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.purchase.total_purchase_amount
     *
     * @mbg.generated
     */
    private Long totalPurchaseAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.purchase.total_purchase_tax_amount
     *
     * @mbg.generated
     */
    private Long totalPurchaseTaxAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.purchase.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.purchase.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.purchase.purchase_number
     *
     * @return the value of inventories.purchase.purchase_number
     * @mbg.generated
     */
    public Integer getPurchaseNumber() {
        return purchaseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.purchase.purchase_number
     *
     * @param purchaseNumber the value for inventories.purchase.purchase_number
     * @mbg.generated
     */
    public void setPurchaseNumber(Integer purchaseNumber) {
        this.purchaseNumber = purchaseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.purchase.purchase_date
     *
     * @return the value of inventories.purchase.purchase_date
     * @mbg.generated
     */
    public Date getPurchaseDate() {
        return purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.purchase.purchase_date
     *
     * @param purchaseDate the value for inventories.purchase.purchase_date
     * @mbg.generated
     */
    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.purchase.supplier_number
     *
     * @return the value of inventories.purchase.supplier_number
     * @mbg.generated
     */
    public Integer getSupplierNumber() {
        return supplierNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.purchase.supplier_number
     *
     * @param supplierNumber the value for inventories.purchase.supplier_number
     * @mbg.generated
     */
    public void setSupplierNumber(Integer supplierNumber) {
        this.supplierNumber = supplierNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.purchase.supplier_line_number
     *
     * @return the value of inventories.purchase.supplier_line_number
     * @mbg.generated
     */
    public Integer getSupplierLineNumber() {
        return supplierLineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.purchase.supplier_line_number
     *
     * @param supplierLineNumber the value for inventories.purchase.supplier_line_number
     * @mbg.generated
     */
    public void setSupplierLineNumber(Integer supplierLineNumber) {
        this.supplierLineNumber = supplierLineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.purchase.total_purchase_amount
     *
     * @return the value of inventories.purchase.total_purchase_amount
     * @mbg.generated
     */
    public Long getTotalPurchaseAmount() {
        return totalPurchaseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.purchase.total_purchase_amount
     *
     * @param totalPurchaseAmount the value for inventories.purchase.total_purchase_amount
     * @mbg.generated
     */
    public void setTotalPurchaseAmount(Long totalPurchaseAmount) {
        this.totalPurchaseAmount = totalPurchaseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.purchase.total_purchase_tax_amount
     *
     * @return the value of inventories.purchase.total_purchase_tax_amount
     * @mbg.generated
     */
    public Long getTotalPurchaseTaxAmount() {
        return totalPurchaseTaxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.purchase.total_purchase_tax_amount
     *
     * @param totalPurchaseTaxAmount the value for inventories.purchase.total_purchase_tax_amount
     * @mbg.generated
     */
    public void setTotalPurchaseTaxAmount(Long totalPurchaseTaxAmount) {
        this.totalPurchaseTaxAmount = totalPurchaseTaxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.purchase.created_by
     *
     * @return the value of inventories.purchase.created_by
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.purchase.created_by
     *
     * @param createdBy the value for inventories.purchase.created_by
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.purchase.created_at
     *
     * @return the value of inventories.purchase.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.purchase.created_at
     *
     * @param createdAt the value for inventories.purchase.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}
