package bouquet.domain.model.autogen.inventories;

import java.util.Date;

public class Supplier {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.supplier.supplier_number
     *
     * @mbg.generated
     */
    private Integer supplierNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.supplier.supplier_line_number
     *
     * @mbg.generated
     */
    private Integer supplierLineNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.supplier.supplier_code
     *
     * @mbg.generated
     */
    private String supplierCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.supplier.supplier_name
     *
     * @mbg.generated
     */
    private String supplierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.supplier.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventories.supplier.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.supplier.supplier_number
     *
     * @return the value of inventories.supplier.supplier_number
     * @mbg.generated
     */
    public Integer getSupplierNumber() {
        return supplierNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.supplier.supplier_number
     *
     * @param supplierNumber the value for inventories.supplier.supplier_number
     * @mbg.generated
     */
    public void setSupplierNumber(Integer supplierNumber) {
        this.supplierNumber = supplierNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.supplier.supplier_line_number
     *
     * @return the value of inventories.supplier.supplier_line_number
     * @mbg.generated
     */
    public Integer getSupplierLineNumber() {
        return supplierLineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.supplier.supplier_line_number
     *
     * @param supplierLineNumber the value for inventories.supplier.supplier_line_number
     * @mbg.generated
     */
    public void setSupplierLineNumber(Integer supplierLineNumber) {
        this.supplierLineNumber = supplierLineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.supplier.supplier_code
     *
     * @return the value of inventories.supplier.supplier_code
     * @mbg.generated
     */
    public String getSupplierCode() {
        return supplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.supplier.supplier_code
     *
     * @param supplierCode the value for inventories.supplier.supplier_code
     * @mbg.generated
     */
    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.supplier.supplier_name
     *
     * @return the value of inventories.supplier.supplier_name
     * @mbg.generated
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.supplier.supplier_name
     *
     * @param supplierName the value for inventories.supplier.supplier_name
     * @mbg.generated
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.supplier.created_by
     *
     * @return the value of inventories.supplier.created_by
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.supplier.created_by
     *
     * @param createdBy the value for inventories.supplier.created_by
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventories.supplier.created_at
     *
     * @return the value of inventories.supplier.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventories.supplier.created_at
     *
     * @param createdAt the value for inventories.supplier.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}
