package bouquet.infrastructure.datasource.autogen.auth;

import bouquet.domain.model.autogen.auth.Usr;
import org.apache.ibatis.annotations.*;

@Mapper
public interface UsrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth.usr
     *
     * @mbg.generated
     */
    @Delete({
            "delete from auth.usr",
            "where user_id = #{userId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth.usr
     *
     * @mbg.generated
     */
    @Insert({
            "insert into auth.usr (user_id, first_name, ",
            "last_name, password, ",
            "role_name)",
            "values (#{userId,jdbcType=VARCHAR}, #{firstName,jdbcType=VARCHAR}, ",
            "#{lastName,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
            "#{roleName,jdbcType=VARCHAR})"
    })
    int insert(Usr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth.usr
     *
     * @mbg.generated
     */
    int insertSelective(Usr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth.usr
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "user_id, first_name, last_name, password, role_name",
            "from auth.usr",
            "where user_id = #{userId,jdbcType=VARCHAR}"
    })
    @ResultMap("bouquet.infrastructure.datasource.autogen.auth.UsrMapper.BaseResultMap")
    Usr selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth.usr
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Usr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth.usr
     *
     * @mbg.generated
     */
    @Update({
            "update auth.usr",
            "set first_name = #{firstName,jdbcType=VARCHAR},",
            "last_name = #{lastName,jdbcType=VARCHAR},",
            "password = #{password,jdbcType=VARCHAR},",
            "role_name = #{roleName,jdbcType=VARCHAR}",
            "where user_id = #{userId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Usr record);
}
