package bouquet.domain.model.autogen.orders;

import java.util.Date;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.customer.customer_number
     *
     * @mbg.generated
     */
    private Integer customerNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.customer.customer_code
     *
     * @mbg.generated
     */
    private String customerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.customer.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.customer.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.customer.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.customer.first_name
     *
     * @mbg.generated
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.customer.last_name
     *
     * @mbg.generated
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.customer.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.customer.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.customer.gender
     *
     * @mbg.generated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.customer.zip
     *
     * @mbg.generated
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.customer.prefecture
     *
     * @mbg.generated
     */
    private String prefecture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.customer.address_1
     *
     * @mbg.generated
     */
    private String address1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.customer.address_2
     *
     * @mbg.generated
     */
    private String address2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.customer.telephone_number
     *
     * @mbg.generated
     */
    private String telephoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.customer.withdraw
     *
     * @mbg.generated
     */
    private Date withdraw;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.customer.customer_number
     *
     * @return the value of orders.customer.customer_number
     * @mbg.generated
     */
    public Integer getCustomerNumber() {
        return customerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.customer.customer_number
     *
     * @param customerNumber the value for orders.customer.customer_number
     * @mbg.generated
     */
    public void setCustomerNumber(Integer customerNumber) {
        this.customerNumber = customerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.customer.customer_code
     *
     * @return the value of orders.customer.customer_code
     * @mbg.generated
     */
    public String getCustomerCode() {
        return customerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.customer.customer_code
     *
     * @param customerCode the value for orders.customer.customer_code
     * @mbg.generated
     */
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.customer.created_by
     *
     * @return the value of orders.customer.created_by
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.customer.created_by
     *
     * @param createdBy the value for orders.customer.created_by
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.customer.created_at
     *
     * @return the value of orders.customer.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.customer.created_at
     *
     * @param createdAt the value for orders.customer.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.customer.user_id
     *
     * @return the value of orders.customer.user_id
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.customer.user_id
     *
     * @param userId the value for orders.customer.user_id
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.customer.first_name
     *
     * @return the value of orders.customer.first_name
     * @mbg.generated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.customer.first_name
     *
     * @param firstName the value for orders.customer.first_name
     * @mbg.generated
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.customer.last_name
     *
     * @return the value of orders.customer.last_name
     * @mbg.generated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.customer.last_name
     *
     * @param lastName the value for orders.customer.last_name
     * @mbg.generated
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.customer.email
     *
     * @return the value of orders.customer.email
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.customer.email
     *
     * @param email the value for orders.customer.email
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.customer.birthday
     *
     * @return the value of orders.customer.birthday
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.customer.birthday
     *
     * @param birthday the value for orders.customer.birthday
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.customer.gender
     *
     * @return the value of orders.customer.gender
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.customer.gender
     *
     * @param gender the value for orders.customer.gender
     * @mbg.generated
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.customer.zip
     *
     * @return the value of orders.customer.zip
     * @mbg.generated
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.customer.zip
     *
     * @param zip the value for orders.customer.zip
     * @mbg.generated
     */
    public void setZip(String zip) {
        this.zip = zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.customer.prefecture
     *
     * @return the value of orders.customer.prefecture
     * @mbg.generated
     */
    public String getPrefecture() {
        return prefecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.customer.prefecture
     *
     * @param prefecture the value for orders.customer.prefecture
     * @mbg.generated
     */
    public void setPrefecture(String prefecture) {
        this.prefecture = prefecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.customer.address_1
     *
     * @return the value of orders.customer.address_1
     * @mbg.generated
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.customer.address_1
     *
     * @param address1 the value for orders.customer.address_1
     * @mbg.generated
     */
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.customer.address_2
     *
     * @return the value of orders.customer.address_2
     * @mbg.generated
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.customer.address_2
     *
     * @param address2 the value for orders.customer.address_2
     * @mbg.generated
     */
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.customer.telephone_number
     *
     * @return the value of orders.customer.telephone_number
     * @mbg.generated
     */
    public String getTelephoneNumber() {
        return telephoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.customer.telephone_number
     *
     * @param telephoneNumber the value for orders.customer.telephone_number
     * @mbg.generated
     */
    public void setTelephoneNumber(String telephoneNumber) {
        this.telephoneNumber = telephoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.customer.withdraw
     *
     * @return the value of orders.customer.withdraw
     * @mbg.generated
     */
    public Date getWithdraw() {
        return withdraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.customer.withdraw
     *
     * @param withdraw the value for orders.customer.withdraw
     * @mbg.generated
     */
    public void setWithdraw(Date withdraw) {
        this.withdraw = withdraw;
    }
}
