package bouquet.domain.model.autogen.orders;

import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.product.product_number
     *
     * @mbg.generated
     */
    private Integer productNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.product.product_code
     *
     * @mbg.generated
     */
    private String productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.product.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.product.product_name_short
     *
     * @mbg.generated
     */
    private String productNameShort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.product.product_type
     *
     * @mbg.generated
     */
    private String productType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.product.sales_price
     *
     * @mbg.generated
     */
    private Integer salesPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.product.cost_price
     *
     * @mbg.generated
     */
    private Integer costPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.product.tax_type
     *
     * @mbg.generated
     */
    private String taxType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.product.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.product.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.product.supplier_number
     *
     * @mbg.generated
     */
    private Integer supplierNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.product.supplier_line_number
     *
     * @mbg.generated
     */
    private Integer supplierLineNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.product.product_number
     *
     * @return the value of orders.product.product_number
     * @mbg.generated
     */
    public Integer getProductNumber() {
        return productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.product.product_number
     *
     * @param productNumber the value for orders.product.product_number
     * @mbg.generated
     */
    public void setProductNumber(Integer productNumber) {
        this.productNumber = productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.product.product_code
     *
     * @return the value of orders.product.product_code
     * @mbg.generated
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.product.product_code
     *
     * @param productCode the value for orders.product.product_code
     * @mbg.generated
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.product.product_name
     *
     * @return the value of orders.product.product_name
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.product.product_name
     *
     * @param productName the value for orders.product.product_name
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.product.product_name_short
     *
     * @return the value of orders.product.product_name_short
     * @mbg.generated
     */
    public String getProductNameShort() {
        return productNameShort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.product.product_name_short
     *
     * @param productNameShort the value for orders.product.product_name_short
     * @mbg.generated
     */
    public void setProductNameShort(String productNameShort) {
        this.productNameShort = productNameShort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.product.product_type
     *
     * @return the value of orders.product.product_type
     * @mbg.generated
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.product.product_type
     *
     * @param productType the value for orders.product.product_type
     * @mbg.generated
     */
    public void setProductType(String productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.product.sales_price
     *
     * @return the value of orders.product.sales_price
     * @mbg.generated
     */
    public Integer getSalesPrice() {
        return salesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.product.sales_price
     *
     * @param salesPrice the value for orders.product.sales_price
     * @mbg.generated
     */
    public void setSalesPrice(Integer salesPrice) {
        this.salesPrice = salesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.product.cost_price
     *
     * @return the value of orders.product.cost_price
     * @mbg.generated
     */
    public Integer getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.product.cost_price
     *
     * @param costPrice the value for orders.product.cost_price
     * @mbg.generated
     */
    public void setCostPrice(Integer costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.product.tax_type
     *
     * @return the value of orders.product.tax_type
     * @mbg.generated
     */
    public String getTaxType() {
        return taxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.product.tax_type
     *
     * @param taxType the value for orders.product.tax_type
     * @mbg.generated
     */
    public void setTaxType(String taxType) {
        this.taxType = taxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.product.created_by
     *
     * @return the value of orders.product.created_by
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.product.created_by
     *
     * @param createdBy the value for orders.product.created_by
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.product.created_at
     *
     * @return the value of orders.product.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.product.created_at
     *
     * @param createdAt the value for orders.product.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.product.supplier_number
     *
     * @return the value of orders.product.supplier_number
     * @mbg.generated
     */
    public Integer getSupplierNumber() {
        return supplierNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.product.supplier_number
     *
     * @param supplierNumber the value for orders.product.supplier_number
     * @mbg.generated
     */
    public void setSupplierNumber(Integer supplierNumber) {
        this.supplierNumber = supplierNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.product.supplier_line_number
     *
     * @return the value of orders.product.supplier_line_number
     * @mbg.generated
     */
    public Integer getSupplierLineNumber() {
        return supplierLineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.product.supplier_line_number
     *
     * @param supplierLineNumber the value for orders.product.supplier_line_number
     * @mbg.generated
     */
    public void setSupplierLineNumber(Integer supplierLineNumber) {
        this.supplierLineNumber = supplierLineNumber;
    }
}
