package bouquet.domain.model.autogen.orders;

import java.util.Date;

public class ReceivedOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.received_order.order_number
     *
     * @mbg.generated
     */
    private Integer orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.received_order.order_date
     *
     * @mbg.generated
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.received_order.customer_number
     *
     * @mbg.generated
     */
    private Integer customerNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.received_order.order_delivery_date_desire
     *
     * @mbg.generated
     */
    private Date orderDeliveryDateDesire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.received_order.order_total_price_amount
     *
     * @mbg.generated
     */
    private Long orderTotalPriceAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.received_order.order_total_tax_amount
     *
     * @mbg.generated
     */
    private Long orderTotalTaxAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.received_order.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.received_order.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.received_order.order_number
     *
     * @return the value of orders.received_order.order_number
     * @mbg.generated
     */
    public Integer getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.received_order.order_number
     *
     * @param orderNumber the value for orders.received_order.order_number
     * @mbg.generated
     */
    public void setOrderNumber(Integer orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.received_order.order_date
     *
     * @return the value of orders.received_order.order_date
     * @mbg.generated
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.received_order.order_date
     *
     * @param orderDate the value for orders.received_order.order_date
     * @mbg.generated
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.received_order.customer_number
     *
     * @return the value of orders.received_order.customer_number
     * @mbg.generated
     */
    public Integer getCustomerNumber() {
        return customerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.received_order.customer_number
     *
     * @param customerNumber the value for orders.received_order.customer_number
     * @mbg.generated
     */
    public void setCustomerNumber(Integer customerNumber) {
        this.customerNumber = customerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.received_order.order_delivery_date_desire
     *
     * @return the value of orders.received_order.order_delivery_date_desire
     * @mbg.generated
     */
    public Date getOrderDeliveryDateDesire() {
        return orderDeliveryDateDesire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.received_order.order_delivery_date_desire
     *
     * @param orderDeliveryDateDesire the value for orders.received_order.order_delivery_date_desire
     * @mbg.generated
     */
    public void setOrderDeliveryDateDesire(Date orderDeliveryDateDesire) {
        this.orderDeliveryDateDesire = orderDeliveryDateDesire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.received_order.order_total_price_amount
     *
     * @return the value of orders.received_order.order_total_price_amount
     * @mbg.generated
     */
    public Long getOrderTotalPriceAmount() {
        return orderTotalPriceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.received_order.order_total_price_amount
     *
     * @param orderTotalPriceAmount the value for orders.received_order.order_total_price_amount
     * @mbg.generated
     */
    public void setOrderTotalPriceAmount(Long orderTotalPriceAmount) {
        this.orderTotalPriceAmount = orderTotalPriceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.received_order.order_total_tax_amount
     *
     * @return the value of orders.received_order.order_total_tax_amount
     * @mbg.generated
     */
    public Long getOrderTotalTaxAmount() {
        return orderTotalTaxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.received_order.order_total_tax_amount
     *
     * @param orderTotalTaxAmount the value for orders.received_order.order_total_tax_amount
     * @mbg.generated
     */
    public void setOrderTotalTaxAmount(Long orderTotalTaxAmount) {
        this.orderTotalTaxAmount = orderTotalTaxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.received_order.created_by
     *
     * @return the value of orders.received_order.created_by
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.received_order.created_by
     *
     * @param createdBy the value for orders.received_order.created_by
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.received_order.created_at
     *
     * @return the value of orders.received_order.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.received_order.created_at
     *
     * @param createdAt the value for orders.received_order.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}
