package bouquet.domain.model.autogen.orders;

import java.util.Date;

public class ReceivedOrderLine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.received_order_line.order_number
     *
     * @mbg.generated
     */
    private Integer orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.received_order_line.order_line_number
     *
     * @mbg.generated
     */
    private Integer orderLineNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.received_order_line.product_number
     *
     * @mbg.generated
     */
    private Integer productNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.received_order_line.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.received_order_line.sales_price
     *
     * @mbg.generated
     */
    private Integer salesPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.received_order_line.order_line_delivery_date
     *
     * @mbg.generated
     */
    private Date orderLineDeliveryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.received_order_line.order_line_quantity
     *
     * @mbg.generated
     */
    private Integer orderLineQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.received_order_line.order_line_tax
     *
     * @mbg.generated
     */
    private Short orderLineTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.received_order_line.order_line_discount
     *
     * @mbg.generated
     */
    private Short orderLineDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.received_order_line.reserve_quantity
     *
     * @mbg.generated
     */
    private Integer reserveQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.received_order_line.shipping_instructing_quantity
     *
     * @mbg.generated
     */
    private Integer shippingInstructingQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.received_order_line.shipping_quantity
     *
     * @mbg.generated
     */
    private Integer shippingQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.received_order_line.complete
     *
     * @mbg.generated
     */
    private Integer complete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.received_order_line.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.received_order_line.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.received_order_line.order_number
     *
     * @return the value of orders.received_order_line.order_number
     * @mbg.generated
     */
    public Integer getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.received_order_line.order_number
     *
     * @param orderNumber the value for orders.received_order_line.order_number
     * @mbg.generated
     */
    public void setOrderNumber(Integer orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.received_order_line.order_line_number
     *
     * @return the value of orders.received_order_line.order_line_number
     * @mbg.generated
     */
    public Integer getOrderLineNumber() {
        return orderLineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.received_order_line.order_line_number
     *
     * @param orderLineNumber the value for orders.received_order_line.order_line_number
     * @mbg.generated
     */
    public void setOrderLineNumber(Integer orderLineNumber) {
        this.orderLineNumber = orderLineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.received_order_line.product_number
     *
     * @return the value of orders.received_order_line.product_number
     * @mbg.generated
     */
    public Integer getProductNumber() {
        return productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.received_order_line.product_number
     *
     * @param productNumber the value for orders.received_order_line.product_number
     * @mbg.generated
     */
    public void setProductNumber(Integer productNumber) {
        this.productNumber = productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.received_order_line.product_name
     *
     * @return the value of orders.received_order_line.product_name
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.received_order_line.product_name
     *
     * @param productName the value for orders.received_order_line.product_name
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.received_order_line.sales_price
     *
     * @return the value of orders.received_order_line.sales_price
     * @mbg.generated
     */
    public Integer getSalesPrice() {
        return salesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.received_order_line.sales_price
     *
     * @param salesPrice the value for orders.received_order_line.sales_price
     * @mbg.generated
     */
    public void setSalesPrice(Integer salesPrice) {
        this.salesPrice = salesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.received_order_line.order_line_delivery_date
     *
     * @return the value of orders.received_order_line.order_line_delivery_date
     * @mbg.generated
     */
    public Date getOrderLineDeliveryDate() {
        return orderLineDeliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.received_order_line.order_line_delivery_date
     *
     * @param orderLineDeliveryDate the value for orders.received_order_line.order_line_delivery_date
     * @mbg.generated
     */
    public void setOrderLineDeliveryDate(Date orderLineDeliveryDate) {
        this.orderLineDeliveryDate = orderLineDeliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.received_order_line.order_line_quantity
     *
     * @return the value of orders.received_order_line.order_line_quantity
     * @mbg.generated
     */
    public Integer getOrderLineQuantity() {
        return orderLineQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.received_order_line.order_line_quantity
     *
     * @param orderLineQuantity the value for orders.received_order_line.order_line_quantity
     * @mbg.generated
     */
    public void setOrderLineQuantity(Integer orderLineQuantity) {
        this.orderLineQuantity = orderLineQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.received_order_line.order_line_tax
     *
     * @return the value of orders.received_order_line.order_line_tax
     * @mbg.generated
     */
    public Short getOrderLineTax() {
        return orderLineTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.received_order_line.order_line_tax
     *
     * @param orderLineTax the value for orders.received_order_line.order_line_tax
     * @mbg.generated
     */
    public void setOrderLineTax(Short orderLineTax) {
        this.orderLineTax = orderLineTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.received_order_line.order_line_discount
     *
     * @return the value of orders.received_order_line.order_line_discount
     * @mbg.generated
     */
    public Short getOrderLineDiscount() {
        return orderLineDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.received_order_line.order_line_discount
     *
     * @param orderLineDiscount the value for orders.received_order_line.order_line_discount
     * @mbg.generated
     */
    public void setOrderLineDiscount(Short orderLineDiscount) {
        this.orderLineDiscount = orderLineDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.received_order_line.reserve_quantity
     *
     * @return the value of orders.received_order_line.reserve_quantity
     * @mbg.generated
     */
    public Integer getReserveQuantity() {
        return reserveQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.received_order_line.reserve_quantity
     *
     * @param reserveQuantity the value for orders.received_order_line.reserve_quantity
     * @mbg.generated
     */
    public void setReserveQuantity(Integer reserveQuantity) {
        this.reserveQuantity = reserveQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.received_order_line.shipping_instructing_quantity
     *
     * @return the value of orders.received_order_line.shipping_instructing_quantity
     * @mbg.generated
     */
    public Integer getShippingInstructingQuantity() {
        return shippingInstructingQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.received_order_line.shipping_instructing_quantity
     *
     * @param shippingInstructingQuantity the value for orders.received_order_line.shipping_instructing_quantity
     * @mbg.generated
     */
    public void setShippingInstructingQuantity(Integer shippingInstructingQuantity) {
        this.shippingInstructingQuantity = shippingInstructingQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.received_order_line.shipping_quantity
     *
     * @return the value of orders.received_order_line.shipping_quantity
     * @mbg.generated
     */
    public Integer getShippingQuantity() {
        return shippingQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.received_order_line.shipping_quantity
     *
     * @param shippingQuantity the value for orders.received_order_line.shipping_quantity
     * @mbg.generated
     */
    public void setShippingQuantity(Integer shippingQuantity) {
        this.shippingQuantity = shippingQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.received_order_line.complete
     *
     * @return the value of orders.received_order_line.complete
     * @mbg.generated
     */
    public Integer getComplete() {
        return complete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.received_order_line.complete
     *
     * @param complete the value for orders.received_order_line.complete
     * @mbg.generated
     */
    public void setComplete(Integer complete) {
        this.complete = complete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.received_order_line.created_by
     *
     * @return the value of orders.received_order_line.created_by
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.received_order_line.created_by
     *
     * @param createdBy the value for orders.received_order_line.created_by
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.received_order_line.created_at
     *
     * @return the value of orders.received_order_line.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.received_order_line.created_at
     *
     * @param createdAt the value for orders.received_order_line.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}
