package bouquet.domain.model.autogen.orders;

import java.util.Date;

public class Sales {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sales.sales_number
     *
     * @mbg.generated
     */
    private Integer salesNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sales.shipping_number
     *
     * @mbg.generated
     */
    private Integer shippingNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sales.sales_date
     *
     * @mbg.generated
     */
    private Date salesDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sales.total_sales_amount
     *
     * @mbg.generated
     */
    private Integer totalSalesAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sales.total_sales_tax_amount
     *
     * @mbg.generated
     */
    private Short totalSalesTaxAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sales.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sales.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sales.sales_number
     *
     * @return the value of orders.sales.sales_number
     * @mbg.generated
     */
    public Integer getSalesNumber() {
        return salesNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sales.sales_number
     *
     * @param salesNumber the value for orders.sales.sales_number
     * @mbg.generated
     */
    public void setSalesNumber(Integer salesNumber) {
        this.salesNumber = salesNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sales.shipping_number
     *
     * @return the value of orders.sales.shipping_number
     * @mbg.generated
     */
    public Integer getShippingNumber() {
        return shippingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sales.shipping_number
     *
     * @param shippingNumber the value for orders.sales.shipping_number
     * @mbg.generated
     */
    public void setShippingNumber(Integer shippingNumber) {
        this.shippingNumber = shippingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sales.sales_date
     *
     * @return the value of orders.sales.sales_date
     * @mbg.generated
     */
    public Date getSalesDate() {
        return salesDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sales.sales_date
     *
     * @param salesDate the value for orders.sales.sales_date
     * @mbg.generated
     */
    public void setSalesDate(Date salesDate) {
        this.salesDate = salesDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sales.total_sales_amount
     *
     * @return the value of orders.sales.total_sales_amount
     * @mbg.generated
     */
    public Integer getTotalSalesAmount() {
        return totalSalesAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sales.total_sales_amount
     *
     * @param totalSalesAmount the value for orders.sales.total_sales_amount
     * @mbg.generated
     */
    public void setTotalSalesAmount(Integer totalSalesAmount) {
        this.totalSalesAmount = totalSalesAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sales.total_sales_tax_amount
     *
     * @return the value of orders.sales.total_sales_tax_amount
     * @mbg.generated
     */
    public Short getTotalSalesTaxAmount() {
        return totalSalesTaxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sales.total_sales_tax_amount
     *
     * @param totalSalesTaxAmount the value for orders.sales.total_sales_tax_amount
     * @mbg.generated
     */
    public void setTotalSalesTaxAmount(Short totalSalesTaxAmount) {
        this.totalSalesTaxAmount = totalSalesTaxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sales.created_by
     *
     * @return the value of orders.sales.created_by
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sales.created_by
     *
     * @param createdBy the value for orders.sales.created_by
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sales.created_at
     *
     * @return the value of orders.sales.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sales.created_at
     *
     * @param createdAt the value for orders.sales.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}
