package bouquet.domain.model.autogen.orders;

import java.util.Date;

public class SalesLine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sales_line.sales_number
     *
     * @mbg.generated
     */
    private Integer salesNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sales_line.sales_line_number
     *
     * @mbg.generated
     */
    private Integer salesLineNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sales_line.product_number
     *
     * @mbg.generated
     */
    private Integer productNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sales_line.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sales_line.sales_price
     *
     * @mbg.generated
     */
    private Integer salesPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sales_line.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sales_line.discount
     *
     * @mbg.generated
     */
    private Integer discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sales_line.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sales_line.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sales_line.sales_number
     *
     * @return the value of orders.sales_line.sales_number
     * @mbg.generated
     */
    public Integer getSalesNumber() {
        return salesNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sales_line.sales_number
     *
     * @param salesNumber the value for orders.sales_line.sales_number
     * @mbg.generated
     */
    public void setSalesNumber(Integer salesNumber) {
        this.salesNumber = salesNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sales_line.sales_line_number
     *
     * @return the value of orders.sales_line.sales_line_number
     * @mbg.generated
     */
    public Integer getSalesLineNumber() {
        return salesLineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sales_line.sales_line_number
     *
     * @param salesLineNumber the value for orders.sales_line.sales_line_number
     * @mbg.generated
     */
    public void setSalesLineNumber(Integer salesLineNumber) {
        this.salesLineNumber = salesLineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sales_line.product_number
     *
     * @return the value of orders.sales_line.product_number
     * @mbg.generated
     */
    public Integer getProductNumber() {
        return productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sales_line.product_number
     *
     * @param productNumber the value for orders.sales_line.product_number
     * @mbg.generated
     */
    public void setProductNumber(Integer productNumber) {
        this.productNumber = productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sales_line.product_name
     *
     * @return the value of orders.sales_line.product_name
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sales_line.product_name
     *
     * @param productName the value for orders.sales_line.product_name
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sales_line.sales_price
     *
     * @return the value of orders.sales_line.sales_price
     * @mbg.generated
     */
    public Integer getSalesPrice() {
        return salesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sales_line.sales_price
     *
     * @param salesPrice the value for orders.sales_line.sales_price
     * @mbg.generated
     */
    public void setSalesPrice(Integer salesPrice) {
        this.salesPrice = salesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sales_line.quantity
     *
     * @return the value of orders.sales_line.quantity
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sales_line.quantity
     *
     * @param quantity the value for orders.sales_line.quantity
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sales_line.discount
     *
     * @return the value of orders.sales_line.discount
     * @mbg.generated
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sales_line.discount
     *
     * @param discount the value for orders.sales_line.discount
     * @mbg.generated
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sales_line.created_by
     *
     * @return the value of orders.sales_line.created_by
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sales_line.created_by
     *
     * @param createdBy the value for orders.sales_line.created_by
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sales_line.created_at
     *
     * @return the value of orders.sales_line.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sales_line.created_at
     *
     * @param createdAt the value for orders.sales_line.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}
