package bouquet.domain.model.autogen.orders;

import java.util.Date;

public class ShippedOrderLine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.shipped_order_line.shipping_number
     *
     * @mbg.generated
     */
    private Integer shippingNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.shipped_order_line.shipping_line_number
     *
     * @mbg.generated
     */
    private Integer shippingLineNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.shipped_order_line.product_number
     *
     * @mbg.generated
     */
    private Integer productNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.shipped_order_line.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.shipped_order_line.order_number
     *
     * @mbg.generated
     */
    private Integer orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.shipped_order_line.order_line_number
     *
     * @mbg.generated
     */
    private Integer orderLineNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.shipped_order_line.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.shipped_order_line.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.shipped_order_line.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.shipped_order_line.shipping_number
     *
     * @return the value of orders.shipped_order_line.shipping_number
     * @mbg.generated
     */
    public Integer getShippingNumber() {
        return shippingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.shipped_order_line.shipping_number
     *
     * @param shippingNumber the value for orders.shipped_order_line.shipping_number
     * @mbg.generated
     */
    public void setShippingNumber(Integer shippingNumber) {
        this.shippingNumber = shippingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.shipped_order_line.shipping_line_number
     *
     * @return the value of orders.shipped_order_line.shipping_line_number
     * @mbg.generated
     */
    public Integer getShippingLineNumber() {
        return shippingLineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.shipped_order_line.shipping_line_number
     *
     * @param shippingLineNumber the value for orders.shipped_order_line.shipping_line_number
     * @mbg.generated
     */
    public void setShippingLineNumber(Integer shippingLineNumber) {
        this.shippingLineNumber = shippingLineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.shipped_order_line.product_number
     *
     * @return the value of orders.shipped_order_line.product_number
     * @mbg.generated
     */
    public Integer getProductNumber() {
        return productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.shipped_order_line.product_number
     *
     * @param productNumber the value for orders.shipped_order_line.product_number
     * @mbg.generated
     */
    public void setProductNumber(Integer productNumber) {
        this.productNumber = productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.shipped_order_line.product_name
     *
     * @return the value of orders.shipped_order_line.product_name
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.shipped_order_line.product_name
     *
     * @param productName the value for orders.shipped_order_line.product_name
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.shipped_order_line.order_number
     *
     * @return the value of orders.shipped_order_line.order_number
     * @mbg.generated
     */
    public Integer getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.shipped_order_line.order_number
     *
     * @param orderNumber the value for orders.shipped_order_line.order_number
     * @mbg.generated
     */
    public void setOrderNumber(Integer orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.shipped_order_line.order_line_number
     *
     * @return the value of orders.shipped_order_line.order_line_number
     * @mbg.generated
     */
    public Integer getOrderLineNumber() {
        return orderLineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.shipped_order_line.order_line_number
     *
     * @param orderLineNumber the value for orders.shipped_order_line.order_line_number
     * @mbg.generated
     */
    public void setOrderLineNumber(Integer orderLineNumber) {
        this.orderLineNumber = orderLineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.shipped_order_line.quantity
     *
     * @return the value of orders.shipped_order_line.quantity
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.shipped_order_line.quantity
     *
     * @param quantity the value for orders.shipped_order_line.quantity
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.shipped_order_line.created_by
     *
     * @return the value of orders.shipped_order_line.created_by
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.shipped_order_line.created_by
     *
     * @param createdBy the value for orders.shipped_order_line.created_by
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.shipped_order_line.created_at
     *
     * @return the value of orders.shipped_order_line.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.shipped_order_line.created_at
     *
     * @param createdAt the value for orders.shipped_order_line.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}
