package bouquet.infrastructure.datasource.autogen.orders;

import bouquet.domain.model.autogen.orders.Product;
import org.apache.ibatis.annotations.*;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.product
     *
     * @mbg.generated
     */
    @Delete({
            "delete from orders.product",
            "where product_number = #{productNumber,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer productNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.product
     *
     * @mbg.generated
     */
    @Insert({
            "insert into orders.product (product_number, product_code, ",
            "product_name, product_name_short, ",
            "product_type, sales_price, ",
            "cost_price, tax_type, ",
            "created_by, created_at, ",
            "supplier_number, supplier_line_number)",
            "values (#{productNumber,jdbcType=INTEGER}, #{productCode,jdbcType=VARCHAR}, ",
            "#{productName,jdbcType=VARCHAR}, #{productNameShort,jdbcType=VARCHAR}, ",
            "#{productType,jdbcType=VARCHAR}, #{salesPrice,jdbcType=NUMERIC}, ",
            "#{costPrice,jdbcType=NUMERIC}, #{taxType,jdbcType=VARCHAR}, ",
            "#{createdBy,jdbcType=VARCHAR}, #{createdAt,jdbcType=TIMESTAMP}, ",
            "#{supplierNumber,jdbcType=INTEGER}, #{supplierLineNumber,jdbcType=INTEGER})"
    })
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.product
     *
     * @mbg.generated
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.product
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "product_number, product_code, product_name, product_name_short, product_type, ",
            "sales_price, cost_price, tax_type, created_by, created_at, supplier_number, ",
            "supplier_line_number",
            "from orders.product",
            "where product_number = #{productNumber,jdbcType=INTEGER}"
    })
    @ResultMap("bouquet.infrastructure.datasource.autogen.orders.ProductMapper.BaseResultMap")
    Product selectByPrimaryKey(Integer productNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.product
     *
     * @mbg.generated
     */
    @Update({
            "update orders.product",
            "set product_code = #{productCode,jdbcType=VARCHAR},",
            "product_name = #{productName,jdbcType=VARCHAR},",
            "product_name_short = #{productNameShort,jdbcType=VARCHAR},",
            "product_type = #{productType,jdbcType=VARCHAR},",
            "sales_price = #{salesPrice,jdbcType=NUMERIC},",
            "cost_price = #{costPrice,jdbcType=NUMERIC},",
            "tax_type = #{taxType,jdbcType=VARCHAR},",
            "created_by = #{createdBy,jdbcType=VARCHAR},",
            "created_at = #{createdAt,jdbcType=TIMESTAMP},",
            "supplier_number = #{supplierNumber,jdbcType=INTEGER},",
            "supplier_line_number = #{supplierLineNumber,jdbcType=INTEGER}",
            "where product_number = #{productNumber,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Product record);
}
