package bouquet.infrastructure.datasource.autogen.orders;

import bouquet.domain.model.autogen.orders.ReceivedOrder;
import org.apache.ibatis.annotations.*;

public interface ReceivedOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.received_order
     *
     * @mbg.generated
     */
    @Delete({
            "delete from orders.received_order",
            "where order_number = #{orderNumber,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer orderNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.received_order
     *
     * @mbg.generated
     */
    @Insert({
            "insert into orders.received_order (order_number, order_date, ",
            "customer_number, order_delivery_date_desire, ",
            "order_total_price_amount, order_total_tax_amount, ",
            "created_by, created_at)",
            "values (#{orderNumber,jdbcType=INTEGER}, #{orderDate,jdbcType=DATE}, ",
            "#{customerNumber,jdbcType=INTEGER}, #{orderDeliveryDateDesire,jdbcType=TIMESTAMP}, ",
            "#{orderTotalPriceAmount,jdbcType=NUMERIC}, #{orderTotalTaxAmount,jdbcType=NUMERIC}, ",
            "#{createdBy,jdbcType=VARCHAR}, #{createdAt,jdbcType=TIMESTAMP})"
    })
    int insert(ReceivedOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.received_order
     *
     * @mbg.generated
     */
    int insertSelective(ReceivedOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.received_order
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "order_number, order_date, customer_number, order_delivery_date_desire, order_total_price_amount, ",
            "order_total_tax_amount, created_by, created_at",
            "from orders.received_order",
            "where order_number = #{orderNumber,jdbcType=INTEGER}"
    })
    @ResultMap("bouquet.infrastructure.datasource.autogen.orders.ReceivedOrderMapper.BaseResultMap")
    ReceivedOrder selectByPrimaryKey(Integer orderNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.received_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReceivedOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.received_order
     *
     * @mbg.generated
     */
    @Update({
            "update orders.received_order",
            "set order_date = #{orderDate,jdbcType=DATE},",
            "customer_number = #{customerNumber,jdbcType=INTEGER},",
            "order_delivery_date_desire = #{orderDeliveryDateDesire,jdbcType=TIMESTAMP},",
            "order_total_price_amount = #{orderTotalPriceAmount,jdbcType=NUMERIC},",
            "order_total_tax_amount = #{orderTotalTaxAmount,jdbcType=NUMERIC},",
            "created_by = #{createdBy,jdbcType=VARCHAR},",
            "created_at = #{createdAt,jdbcType=TIMESTAMP}",
            "where order_number = #{orderNumber,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ReceivedOrder record);
}
