package bouquet.infrastructure.datasource.autogen.orders;

import bouquet.domain.model.autogen.orders.SalesLine;
import org.apache.ibatis.annotations.*;

public interface SalesLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.sales_line
     *
     * @mbg.generated
     */
    @Delete({
            "delete from orders.sales_line",
            "where sales_number = #{salesNumber,jdbcType=INTEGER}",
            "and sales_line_number = #{salesLineNumber,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(@Param("salesNumber") Integer salesNumber, @Param("salesLineNumber") Integer salesLineNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.sales_line
     *
     * @mbg.generated
     */
    @Insert({
            "insert into orders.sales_line (sales_number, sales_line_number, ",
            "product_number, product_name, ",
            "sales_price, quantity, ",
            "discount, created_by, ",
            "created_at)",
            "values (#{salesNumber,jdbcType=INTEGER}, #{salesLineNumber,jdbcType=INTEGER}, ",
            "#{productNumber,jdbcType=INTEGER}, #{productName,jdbcType=VARCHAR}, ",
            "#{salesPrice,jdbcType=NUMERIC}, #{quantity,jdbcType=INTEGER}, ",
            "#{discount,jdbcType=NUMERIC}, #{createdBy,jdbcType=VARCHAR}, ",
            "#{createdAt,jdbcType=TIMESTAMP})"
    })
    int insert(SalesLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.sales_line
     *
     * @mbg.generated
     */
    int insertSelective(SalesLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.sales_line
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "sales_number, sales_line_number, product_number, product_name, sales_price, ",
            "quantity, discount, created_by, created_at",
            "from orders.sales_line",
            "where sales_number = #{salesNumber,jdbcType=INTEGER}",
            "and sales_line_number = #{salesLineNumber,jdbcType=INTEGER}"
    })
    @ResultMap("bouquet.infrastructure.datasource.autogen.orders.SalesLineMapper.BaseResultMap")
    SalesLine selectByPrimaryKey(@Param("salesNumber") Integer salesNumber, @Param("salesLineNumber") Integer salesLineNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.sales_line
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SalesLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.sales_line
     *
     * @mbg.generated
     */
    @Update({
            "update orders.sales_line",
            "set product_number = #{productNumber,jdbcType=INTEGER},",
            "product_name = #{productName,jdbcType=VARCHAR},",
            "sales_price = #{salesPrice,jdbcType=NUMERIC},",
            "quantity = #{quantity,jdbcType=INTEGER},",
            "discount = #{discount,jdbcType=NUMERIC},",
            "created_by = #{createdBy,jdbcType=VARCHAR},",
            "created_at = #{createdAt,jdbcType=TIMESTAMP}",
            "where sales_number = #{salesNumber,jdbcType=INTEGER}",
            "and sales_line_number = #{salesLineNumber,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SalesLine record);
}
