package bouquet.infrastructure.datasource.autogen.orders;

import bouquet.domain.model.autogen.orders.Sales;
import org.apache.ibatis.annotations.*;

public interface SalesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.sales
     *
     * @mbg.generated
     */
    @Delete({
            "delete from orders.sales",
            "where sales_number = #{salesNumber,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer salesNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.sales
     *
     * @mbg.generated
     */
    @Insert({
            "insert into orders.sales (sales_number, shipping_number, ",
            "sales_date, total_sales_amount, ",
            "total_sales_tax_amount, created_by, ",
            "created_at)",
            "values (#{salesNumber,jdbcType=INTEGER}, #{shippingNumber,jdbcType=INTEGER}, ",
            "#{salesDate,jdbcType=DATE}, #{totalSalesAmount,jdbcType=NUMERIC}, ",
            "#{totalSalesTaxAmount,jdbcType=NUMERIC}, #{createdBy,jdbcType=VARCHAR}, ",
            "#{createdAt,jdbcType=TIMESTAMP})"
    })
    int insert(Sales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.sales
     *
     * @mbg.generated
     */
    int insertSelective(Sales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.sales
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "sales_number, shipping_number, sales_date, total_sales_amount, total_sales_tax_amount, ",
            "created_by, created_at",
            "from orders.sales",
            "where sales_number = #{salesNumber,jdbcType=INTEGER}"
    })
    @ResultMap("bouquet.infrastructure.datasource.autogen.orders.SalesMapper.BaseResultMap")
    Sales selectByPrimaryKey(Integer salesNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.sales
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Sales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.sales
     *
     * @mbg.generated
     */
    @Update({
            "update orders.sales",
            "set shipping_number = #{shippingNumber,jdbcType=INTEGER},",
            "sales_date = #{salesDate,jdbcType=DATE},",
            "total_sales_amount = #{totalSalesAmount,jdbcType=NUMERIC},",
            "total_sales_tax_amount = #{totalSalesTaxAmount,jdbcType=NUMERIC},",
            "created_by = #{createdBy,jdbcType=VARCHAR},",
            "created_at = #{createdAt,jdbcType=TIMESTAMP}",
            "where sales_number = #{salesNumber,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Sales record);
}
