package bouquet.infrastructure.datasource.autogen.orders;

import bouquet.domain.model.autogen.orders.ShippedOrder;
import org.apache.ibatis.annotations.*;

public interface ShippedOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.shipped_order
     *
     * @mbg.generated
     */
    @Delete({
            "delete from orders.shipped_order",
            "where shipping_number = #{shippingNumber,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer shippingNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.shipped_order
     *
     * @mbg.generated
     */
    @Insert({
            "insert into orders.shipped_order (shipping_number, shipping_date, ",
            "customer_number, created_by, ",
            "created_at)",
            "values (#{shippingNumber,jdbcType=INTEGER}, #{shippingDate,jdbcType=DATE}, ",
            "#{customerNumber,jdbcType=INTEGER}, #{createdBy,jdbcType=VARCHAR}, ",
            "#{createdAt,jdbcType=TIMESTAMP})"
    })
    int insert(ShippedOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.shipped_order
     *
     * @mbg.generated
     */
    int insertSelective(ShippedOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.shipped_order
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "shipping_number, shipping_date, customer_number, created_by, created_at",
            "from orders.shipped_order",
            "where shipping_number = #{shippingNumber,jdbcType=INTEGER}"
    })
    @ResultMap("bouquet.infrastructure.datasource.autogen.orders.ShippedOrderMapper.BaseResultMap")
    ShippedOrder selectByPrimaryKey(Integer shippingNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.shipped_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShippedOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders.shipped_order
     *
     * @mbg.generated
     */
    @Update({
            "update orders.shipped_order",
            "set shipping_date = #{shippingDate,jdbcType=DATE},",
            "customer_number = #{customerNumber,jdbcType=INTEGER},",
            "created_by = #{createdBy,jdbcType=VARCHAR},",
            "created_at = #{createdAt,jdbcType=TIMESTAMP}",
            "where shipping_number = #{shippingNumber,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ShippedOrder record);
}
